### ISSUE TITLE
Refactoring with bridges

### ISSUE THREAD

**Issue by blegat** [jump-dev/DiffOpt.jl#167]
I started a new design with https://github.com/jump-dev/DiffOpt.jl/pull/166

Currently, the user needs to either model in a purely conic way or purely QP way to have it work with DiffOpt and we don't want to restrict it to the format understood by DiffOpt as it may be different that the format needed by the optimizer and we don't want to do transformations back and forth.
The idea is that the user model should be directly given to the optimizer with minimal transformation while DiffOpt needs to standardize things into the format it understands with a separate bridging layer that it not applied to the model given to the optimizer.

So in `DiffOpt.Optimizer`, there will be
1. `optimizer`: The optimize with exactly the model the user gave (possibly some bridges there but it's transparent to DiffOpt).
2. `diff`: Either a `LazyBridgeOptimizer{QPDiff}` or a `LazyBridgeOptimizer{ConicDiff}`.

To differentiate,
1. the model is first copied from `optimizer` to `diff`, with bridges applied so that the form is exactly the conic or QP form we can work with.
2. the primal and dual values are passed from the optimizer to the diff, the bridges taking care of transforming them.
3. when the user queries or set a forward or backward info, it go through the bridges so in case that variable/constraint/objective was bridged, it will transform it just like it's a primal or dual information. This will require some changes to MOI.

- [x] Create `diff` subfield https://github.com/jump-dev/DiffOpt.jl/pull/166
- [x] Let `diff` have its own indices https://github.com/jump-dev/DiffOpt.jl/pull/179
- [x] Add a bridge layer for the conic `diff` https://github.com/jump-dev/DiffOpt.jl/pull/184
- [ ] Use matrix form for `QPDiff` https://github.com/jump-dev/DiffOpt.jl/issues/153

**Comment by joaquimg** [comment]
At first glance, this looks **very** nice.

Changes in MOI make me a bit worried about to not be compatible with JuMP 1.x. I don't know what you have in mind,

On a parallel thread, but looking forward...

I imagine that many usages of this project would perform many in-place problem modifications of the problems.
We can imagine something like a gradient descent usage:
0 - Start with some value of some data like a coefficient in the objective
1 - solve model
2 - compute the derivative wrt to the coefficient
3 - update the coefficient
4 - go back to 1

I know that for many conic solvers optimizing such pipeline is not useful since model is always reloaded. But for quadratic like cplex, gurobi, express, osqp this would be very valuable.

This issue is certainly not the place for all that, but it would be good to have that in mind for the new design.

**Comment by blegat** [comment]
> Changes in MOI make me a bit worried about to not be compatible with JuMP 1.x. I don't know what you have in mind

I don't think we would need anything breaking, see the new `src/bridges.jl` file in https://github.com/jump-dev/DiffOpt.jl/pull/184

> This issue is certainly not the place for all that, but it would be good to have that in mind for the new design.

It would require implementing in-place modification for `MOI.Utilities.MatrixOfConstraints` which should be doable.
