### ISSUE TITLE
Wrong indexing using variable_index.value

### ISSUE THREAD

**Issue by matbesancon** [jump-dev/DiffOpt.jl#68]
In get_problem_data
```
        for x in func.terms
            A[i, x.variable_index.value] = x.coefficient
        end
```

^ this assumes variable_index.value is a valid index for variables.
Creating variables and deleting them is enough to make this error

**Comment by blegat** [comment]
We should have a `map_columns` similar to `map_rows` of https://github.com/jump-dev/DiffOpt.jl/pull/62 which uses `index_map` to make sure we use the indices of the conic form which corresponds to continguous column indices instead of the indices of the `model` which can be anything. We should use `MockOptimizer` in the tests, it uses crazy indices to make sure we don't use this assumption.

**Comment by matbesancon** [comment]
OK, we can leave this issue open to add it later

**Comment by matbesancon** [comment]
Just caught another one in the latest commit of #66
